front_end:
    resource: "@FrontEndBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
