<?php

namespace ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantsRepository extends EntityRepository
{
}
